# Generated by Django 5.2.7 on 2025-10-30 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventlog', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='log',
            new_name='eventlog_lo_action_f1a503_idx',
            old_fields=('action', 'timestamp'),
        ),
    ]
