[tox]
envlist =
    ruff
    django42-py{311,312}
    django52-py{311,312,313}

[testenv]
install_command =
    pip install -v -v -v {opts} {packages}
# so setup.py install_requires doesn't overwrite tox deps
use_frozen_constraints=true
constrain_package_deps=true
deps =
    {[base]deps}
    django42: django==4.2.20
    django52: django==5.2.0
commands =
    pytest {posargs}
setenv =
    DJANGO_SETTINGS_MODULE=tests.settings
    PYTHONPATH={toxinidir}
    HOME={env:HOME:/home/runner}

[base]
deps =
    -r{toxinidir}/requirements/requirements-common.txt
    -r{toxinidir}/requirements/requirements-test.txt

[testenv:ruff]
passenv = TERM
deps =
    ruff==0.11.0
commands =
    ruff check .
    ruff format --check .
